# Generated by Django 4.2.30 on 2026-04-22 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_topic_finding_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='FindingComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.finding')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
