# Generated by Django 4.2.30 on 2026-04-28 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_finding_code_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprintitem',
            name='sprint',
        ),
        migrations.RemoveField(
            model_name='standupupdate',
            name='sprint',
        ),
        migrations.RemoveField(
            model_name='finding',
            name='linked_task',
        ),
        migrations.DeleteModel(
            name='Blocker',
        ),
        migrations.DeleteModel(
            name='Sprint',
        ),
        migrations.DeleteModel(
            name='SprintItem',
        ),
        migrations.DeleteModel(
            name='StandupUpdate',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
